#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Net-OpenID-Consumer
Version  : 1.18
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/W/WR/WROG/Net-OpenID-Consumer-1.18.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/W/WR/WROG/Net-OpenID-Consumer-1.18.tar.gz
Summary  : 'Library for consumers of OpenID identities'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Net-OpenID-Consumer-license
BuildRequires : buildreq-cpan
BuildRequires : perl(CGI)
BuildRequires : perl(Crypt::DH::GMP)
BuildRequires : perl(HTML::Parser)
BuildRequires : perl(HTTP::Date)
BuildRequires : perl(HTTP::Request)
BuildRequires : perl(JSON)
BuildRequires : perl(LWP::UserAgent)
BuildRequires : perl(Net::OpenID::Common)
BuildRequires : perl(Try::Tiny)
BuildRequires : perl(URI)
BuildRequires : perl(XML::Simple)

%description
Net-OpenID-Consumer
===================
This is a set of Perl modules for implementing
a Relying Party for OpenID (versions 1.1 or 2.0)

%package dev
Summary: dev components for the perl-Net-OpenID-Consumer package.
Group: Development
Provides: perl-Net-OpenID-Consumer-devel

%description dev
dev components for the perl-Net-OpenID-Consumer package.


%package license
Summary: license components for the perl-Net-OpenID-Consumer package.
Group: Default

%description license
license components for the perl-Net-OpenID-Consumer package.


%prep
%setup -q -n Net-OpenID-Consumer-1.18

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Net-OpenID-Consumer
cp LICENSE %{buildroot}/usr/share/doc/perl-Net-OpenID-Consumer/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Net/OpenID/Association.pm
/usr/lib/perl5/site_perl/5.26.1/Net/OpenID/ClaimedIdentity.pm
/usr/lib/perl5/site_perl/5.26.1/Net/OpenID/Consumer.pm
/usr/lib/perl5/site_perl/5.26.1/Net/OpenID/VerifiedIdentity.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Net::OpenID::Association.3
/usr/share/man/man3/Net::OpenID::ClaimedIdentity.3
/usr/share/man/man3/Net::OpenID::Consumer.3
/usr/share/man/man3/Net::OpenID::VerifiedIdentity.3

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Net-OpenID-Consumer/LICENSE
